# Add a substitutions block at the top to define a reusable variable for our image name
substitutions:
  _IMAGE_NAME: 'us-east1-docker.pkg.dev/extractai-468305/extractai-images/uploader-api'

steps:
# 1. Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', '${_IMAGE_NAME}:$COMMIT_SHA', '.']
  dir: 'uploader-api'

# 2. Push the image to Artifact Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', '${_IMAGE_NAME}:$COMMIT_SHA']
  
# 3. (THE FIX) Generate a complete and valid Cloud Run manifest from scratch.
#    This ensures the manifest always has the required fields.
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'sh'
  args:
  - '-c'
  - |
    echo "apiVersion: serving.knative.dev/v1
    kind: Service
    metadata:
      name: uploader-api
    spec:
      template:
        spec:
          containers:
          - image: ${_IMAGE_NAME}:${COMMIT_SHA}" > cloudrun-service.yaml

# 4. Hand off to Cloud Deploy to start the canary release.
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
    - 'deploy'
    - 'releases'
    - 'create'
    - 'release-${SHORT_SHA}'
    - '--delivery-pipeline=uploader-api-pipeline'
    - '--region=us-east1'
    - '--skaffold-file=skaffold.yaml'
    - '--source=.'

# The 'images' block is no longer strictly necessary as we define it in substitutions,
# but it's good practice for traceability.
images:
- '${_IMAGE_NAME}:$COMMIT_SHA'
options:
  logging: CLOUD_LOGGING_ONLY